### ISSUE TITLE
제안서 리뷰

### ISSUE THREAD

**Issue by MisooKim2** [kjw16911/CPP202309-P#1]
1. 기능이 미흡해 보입니다. 사용자가 원하는 상품이 무제한 나오면 은행 입장에서는 손해일 수 있습니다. 은행 입장에서 미리 상품들을 정의했다고 할 때, 최대한 사용자가 원하는 상품과 유사한 상품이 검색될 수 있도록 기능을 추가하는건 어떨까요?
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by kjw16911** [comment]
#1 네 알겠습니다. 1차 진척보고서에 추가 반영하여 제출하도록 하겠습니다.
